AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ButtleHub Stack

Parameters:
  StageName:
    Type: String
  Suffix:
    Type: String
    Default: ""
  DATABASE_HOST:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'staging/DATABASE_HOST\'
  DATABASE_USER:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'staging/DATABASE_USER\'
  DATABASE_PASSWORD:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'staging/DATABASE_PASSWORD\'

Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,DELETE'"
      AllowHeaders: "'Accept, Accept-Language, Content-Type, Content-Language, Last-Event-ID, Authorization, X-Requested-With, Origin'"
      AllowOrigin: "'*'"
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
  Function:
    Timeout: 30

Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./packages/api/dist/
      Handler: dist/lambda-entry-point.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          NODE_ENV: production
          DATABASE_HOST: !Ref DATABASE_HOST
          DATABASE_USER: !Ref DATABASE_USER
          DATABASE_PASSWORD: !Ref DATABASE_PASSWORD
      Policies:
        - Effect: Allow
          Action:
            - ssm:GetParameters
            - ssm:GetParameter
          Resource: "arn:aws:ssm:us-east-1:435084048873:parameter/your/app/*"
      Events:
        Shop:
          Type: Api
          Properties:
            Method: any
            Path: /shop/graphql
